version: "3.9"
services:
  db_monguito:
    image: mongo
    container_name: db_monguito
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=monguito
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - red_nopalisis

  nopalisis_fut:
    build: .
    ports:
      - "8501:8501"
    links:
      - db_monguito
    depends_on:
      - db_monguito
    networks:
      - red_nopalisis
    volumes:
      - .:/home/app

    
#Si no tenemos creada nuestra red podemos usar estas lineas 
networks:
  red_nopalisis:
    driver: bridge  
