#Esto es un Dockerfile para entorno de produccion

#Elgimos nuestra imagen base con su version respectiva
FROM python:3.12

#Inidicamos quien es el responsable de mantener el contenedor
LABEL Maintainer = "JaviScript"

#Creamos el directorio de la aplicacion
RUN mkdir -p /home/app

#Instalacion de paquetes necesarios para correr Streamlit
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    nano \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

#Modificar el bash
RUN rm /root/.bashrc
COPY .bashrc /root


#Copiar los archivos la aplicacion
COPY . /home/app

#Establecemos el espacio de trabajo
WORKDIR /home/app

#Exponemos el puerto en este caso para streamlit
EXPOSE 8501

#Instalamos las dependencias necesarios para correr el programa
RUN pip install --no-cache-dir -r /home/app/requirements.txt

CMD ["bash"]
